# Generated by Django 6.1 on 2026-08-15 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_category_product_productimage_subcategory_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="SubCategory",
            new_name="subcategory",
        ),
    ]
